# This file was generated by GoReleaser. DO NOT EDIT.
cask "switchboard" do
  version "2026.426.1"

  on_macos do
    on_intel do
      sha256 "8abca38947e3c129992708139efb8936b13cc8285390986d4382b7e0d2606edc"
      url "https://github.com/daltoniam/switchboard/releases/download/v#{version}/switchboard_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1087682280d412fd215a3ea6991093113eba937a916c6f42a1cac0b15caefedb"
      url "https://github.com/daltoniam/switchboard/releases/download/v#{version}/switchboard_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8715a4b2473324d8f2711148ab85e542a0a6ebe8633588a1a3dcfcaaae75c0eb"
      url "https://github.com/daltoniam/switchboard/releases/download/v#{version}/switchboard_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0a900e108cc3ba0f4a95dd966023f2435892e870eb4a0a8c6d9303367b6cd5de"
      url "https://github.com/daltoniam/switchboard/releases/download/v#{version}/switchboard_#{version}_linux_arm64.tar.gz"
    end
  end

  name "switchboard"
  desc "Unified MCP server aggregating 17+ integrations (GitHub, Datadog, Linear, Slack, AWS, GCP, and more) behind a single endpoint"
  homepage "https://github.com/daltoniam/switchboard"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "switchboard"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/switchboard"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    To start the background daemon, run:
      switchboard daemon install

    To uninstall the daemon before removing the cask, run:
      switchboard daemon uninstall
  EOS
end
