# This file was generated by GoReleaser. DO NOT EDIT.
cask "switchboard" do
  version "0.2.4"

  on_macos do
    on_intel do
      url "https://github.com/daltoniam/switchboard/releases/download/v#{version}/switchboard_#{version}_darwin_amd64.tar.gz"
      sha256 "572340fe5d3cf6129af9a9936c72109d707b111a8922e29546ef4d5c0fa3a748"
    end
    on_arm do
      url "https://github.com/daltoniam/switchboard/releases/download/v#{version}/switchboard_#{version}_darwin_arm64.tar.gz"
      sha256 "715bce4d7eefb46fa9e60f5a6193e31ef402eb0e7d7c3cbebbe3e48175e26b61"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/daltoniam/switchboard/releases/download/v#{version}/switchboard_#{version}_linux_amd64.tar.gz"
      sha256 "6d8b5a2800f8b528061ea7606007bc9dd198d0c15a251abd6ee2e0e6072bf65d"
    end
    on_arm do
      url "https://github.com/daltoniam/switchboard/releases/download/v#{version}/switchboard_#{version}_linux_arm64.tar.gz"
      sha256 "7f5f08d5c475b8fddc8eb44c5b3376134068bd086a3611d9283ea350e4a34c76"
    end
  end

  name "switchboard"
  desc "Unified MCP server aggregating 17+ integrations (GitHub, Datadog, Linear, Slack, AWS, GCP, and more) behind a single endpoint"
  homepage "https://github.com/daltoniam/switchboard"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "switchboard"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/switchboard"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    To start the background daemon, run:
      switchboard daemon install

    To uninstall the daemon before removing the cask, run:
      switchboard daemon uninstall
  EOS
end
