# This file was generated by GoReleaser. DO NOT EDIT.
cask "switchboard" do
  version "2026.819.0"

  on_macos do
    on_intel do
      sha256 "960436ccb6df7943dd719446ee4fa9549b25d613cf32bde00bd8057d4ef83140"
      url "https://github.com/daltoniam/switchboard/releases/download/v#{version}/switchboard_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4d790f2ea1f4735ab9eee9fa28d98708ee4b26a3a160e1121976c08c028f60d3"
      url "https://github.com/daltoniam/switchboard/releases/download/v#{version}/switchboard_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5db03a274bcf5e787b3489574ebf5c436a85453394515eadce3b99e2bbe9f73a"
      url "https://github.com/daltoniam/switchboard/releases/download/v#{version}/switchboard_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "db8fcf21293dd4e330cca8ccc9f01855dab9973777b226c36751b922a93bb209"
      url "https://github.com/daltoniam/switchboard/releases/download/v#{version}/switchboard_#{version}_linux_arm64.tar.gz"
    end
  end

  name "switchboard"
  desc "Unified MCP server aggregating 17+ integrations (GitHub, Datadog, Linear, Slack, AWS, GCP, and more) behind a single endpoint"
  homepage "https://github.com/daltoniam/switchboard"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "switchboard"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/switchboard"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    To start the background daemon, run:
      switchboard daemon install

    To uninstall the daemon before removing the cask, run:
      switchboard daemon uninstall
  EOS
end
