# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Overload < Formula
  desc "Self-hosted AI pull request reviews and scheduled agent jobs"
  homepage "https://github.com/daltoniam/overload"
  version "0.1.1"
  license "Apache-2.0"

  depends_on "postgresql@17"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/daltoniam/overload/releases/download/v0.1.1/overload_darwin_amd64.tar.gz"
      sha256 "458381dd364af0df3584bfc4d52b862e527ce9b2a778e4c2e60cb8ef1ce67f61"

      define_method(:install) do
        bin.install "overload"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/daltoniam/overload/releases/download/v0.1.1/overload_darwin_arm64.tar.gz"
      sha256 "d25ff574e931fd06160ea1960167f141d1ee326b36d53cd7023f12f694fe6baa"

      define_method(:install) do
        bin.install "overload"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/daltoniam/overload/releases/download/v0.1.1/overload_linux_amd64.tar.gz"
      sha256 "33926c6a062a2a786c2ad2127f903e7ff6bf1e0654f2fddd941d2ba45c314b68"
      define_method(:install) do
        bin.install "overload"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/daltoniam/overload/releases/download/v0.1.1/overload_linux_arm64.tar.gz"
      sha256 "1642d17cb0f4e5718faf1a00882a463a55907f19b8427b6d35a6e75ab082f6f8"
      define_method(:install) do
        bin.install "overload"
      end
    end
  end

  def caveats
    <<~EOS
      Start overload (a private Postgres plus a login service) with:
        overload install

      It prints the UI address and generated password. Stop it with
      `overload uninstall`; add --purge to delete its data.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/overload version")
  end
end
