# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Overload < Formula
  desc "Self-hosted AI pull request reviews and scheduled agent jobs"
  homepage "https://github.com/daltoniam/overload"
  version "0.5.2"
  license "Apache-2.0"

  depends_on "postgresql@17"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/daltoniam/overload/releases/download/v0.5.2/overload_darwin_amd64.tar.gz"
      sha256 "84855ad0baa9feaf9080780a2c8b6563499884f2f501e3efc39ef85ab24e7d40"

      define_method(:install) do
        bin.install "overload"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/daltoniam/overload/releases/download/v0.5.2/overload_darwin_arm64.tar.gz"
      sha256 "bd7e979e0e4259144fe90276b2a88980c1f16d4e11e1cdc874aa9e005c1fe5a3"

      define_method(:install) do
        bin.install "overload"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/daltoniam/overload/releases/download/v0.5.2/overload_linux_amd64.tar.gz"
      sha256 "e47a48fd07fd3f6f0be7e1e0dbcc0b25e12bad47b025bfaa3bbd3b00d97860b1"
      define_method(:install) do
        bin.install "overload"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/daltoniam/overload/releases/download/v0.5.2/overload_linux_arm64.tar.gz"
      sha256 "e406a404b103313e4384ca94328e6cb6fc66e2b7aa70e23487ad96d3d34d509d"
      define_method(:install) do
        bin.install "overload"
      end
    end
  end

  def caveats
    <<~EOS
      Start overload (a private Postgres plus a login service) with:
        overload install

      It prints the UI address and generated password. Stop it with
      `overload uninstall`; add --purge to delete its data.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/overload version")
  end
end
