# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Overload < Formula
  desc "Self-hosted AI pull request reviews and scheduled agent jobs"
  homepage "https://github.com/daltoniam/overload"
  version "0.4.0"
  license "Apache-2.0"

  depends_on "postgresql@17"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/daltoniam/overload/releases/download/v0.4.0/overload_darwin_amd64.tar.gz"
      sha256 "1fc16fbdf79a5c574d0785f8c41b34145399b1ce8f4709a2c252a90bc663987d"

      define_method(:install) do
        bin.install "overload"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/daltoniam/overload/releases/download/v0.4.0/overload_darwin_arm64.tar.gz"
      sha256 "5f540cbb3608c4c90d886267ad41788d56eae9261aa67df4c8e99cbdab89b31e"

      define_method(:install) do
        bin.install "overload"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/daltoniam/overload/releases/download/v0.4.0/overload_linux_amd64.tar.gz"
      sha256 "c9d0cd212d379fb898fe814d23335416a5ef12c5cd0303deb13040ec8deb237d"
      define_method(:install) do
        bin.install "overload"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/daltoniam/overload/releases/download/v0.4.0/overload_linux_arm64.tar.gz"
      sha256 "daa444837acf89333f0c440890e50c4e814dc1120c0380597a448113ca250154"
      define_method(:install) do
        bin.install "overload"
      end
    end
  end

  def caveats
    <<~EOS
      Start overload (a private Postgres plus a login service) with:
        overload install

      It prints the UI address and generated password. Stop it with
      `overload uninstall`; add --purge to delete its data.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/overload version")
  end
end
