# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Switchboard < Formula
  desc "Unified MCP server aggregating 17+ integrations (GitHub, Datadog, Linear, Slack, AWS, GCP, and more) behind a single endpoint"
  homepage "https://github.com/daltoniam/switchboard"
  version "2026.804.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/daltoniam/switchboard/releases/download/v2026.804.0/switchboard_2026.804.0_darwin_amd64.tar.gz"
      sha256 "d96525ac9a4ce6eb08927701050e03d4d539366bf1252e34f39b37158b0e5eb6"

      define_method(:install) do
        bin.install "switchboard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/daltoniam/switchboard/releases/download/v2026.804.0/switchboard_2026.804.0_darwin_arm64.tar.gz"
      sha256 "6d8bccc906f07fbdf431531299f78183d441401e48a66d91dd0a16fed4d50035"

      define_method(:install) do
        bin.install "switchboard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/daltoniam/switchboard/releases/download/v2026.804.0/switchboard_2026.804.0_linux_amd64.tar.gz"
      sha256 "2ca613dd6ce28de1bbf134a838a88b9b01d64f7c0ab2471d18f2e8f7848ef7d9"
      define_method(:install) do
        bin.install "switchboard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/daltoniam/switchboard/releases/download/v2026.804.0/switchboard_2026.804.0_linux_arm64.tar.gz"
      sha256 "7fb53a792ec1f9565287586707cf1d01c5406bcde3921f2da0b657afbf1f5373"
      define_method(:install) do
        bin.install "switchboard"
      end
    end
  end

  test do
    system "#{bin}/switchboard", "--help"
  end
end
