# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Switchboard < Formula
  desc "Unified MCP server aggregating 17+ integrations (GitHub, Datadog, Linear, Slack, AWS, GCP, and more) behind a single endpoint"
  homepage "https://github.com/daltoniam/switchboard"
  version "2026.509.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/daltoniam/switchboard/releases/download/v2026.509.0/switchboard_2026.509.0_darwin_amd64.tar.gz"
      sha256 "ec2f1ec5b886a2a780c72f9943822c17ca6443fc74b68cf13a11aecf3de39f2d"

      define_method(:install) do
        bin.install "switchboard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/daltoniam/switchboard/releases/download/v2026.509.0/switchboard_2026.509.0_darwin_arm64.tar.gz"
      sha256 "ed2980123051a234074e7378d45212bdc432066244b01fa20dd66fabaabacc7d"

      define_method(:install) do
        bin.install "switchboard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/daltoniam/switchboard/releases/download/v2026.509.0/switchboard_2026.509.0_linux_amd64.tar.gz"
      sha256 "7ada3c063e3eace3f33a576070b18eda02fa31f7f407b81dae3d8b97dfd9a7dc"
      define_method(:install) do
        bin.install "switchboard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/daltoniam/switchboard/releases/download/v2026.509.0/switchboard_2026.509.0_linux_arm64.tar.gz"
      sha256 "6bd14fb7d52c9f1c4fd51c7fb171db5552e9084336ebcdafc5f7bd80813aa6c7"
      define_method(:install) do
        bin.install "switchboard"
      end
    end
  end

  test do
    system "#{bin}/switchboard", "--help"
  end
end
