# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Switchboard < Formula
  desc "Unified MCP server aggregating 17+ integrations (GitHub, Datadog, Linear, Slack, AWS, GCP, and more) behind a single endpoint"
  homepage "https://github.com/daltoniam/switchboard"
  version "2026.520.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/daltoniam/switchboard/releases/download/v2026.520.0/switchboard_2026.520.0_darwin_amd64.tar.gz"
      sha256 "c83c62beeed78f4adca30f1fc12debcb88bb8029b9c588bab512186ba8f645bb"

      define_method(:install) do
        bin.install "switchboard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/daltoniam/switchboard/releases/download/v2026.520.0/switchboard_2026.520.0_darwin_arm64.tar.gz"
      sha256 "66676b0ce16e773555f7328152aaf60b2dab926d5577c0e3e329b5d7d06ebca1"

      define_method(:install) do
        bin.install "switchboard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/daltoniam/switchboard/releases/download/v2026.520.0/switchboard_2026.520.0_linux_amd64.tar.gz"
      sha256 "557e3a5998ee49a7367a6f6d28305e5a14264c956788ab1a61841069cdf06ce1"
      define_method(:install) do
        bin.install "switchboard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/daltoniam/switchboard/releases/download/v2026.520.0/switchboard_2026.520.0_linux_arm64.tar.gz"
      sha256 "242c606599475ed050e7b9e28af3e712df9697b0727d1bc94a2877307a67f7f5"
      define_method(:install) do
        bin.install "switchboard"
      end
    end
  end

  test do
    system "#{bin}/switchboard", "--help"
  end
end
